name: CD Pipeline

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v4
              with:
                  context: .
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/lb-discord-bot:latest

            - name: Deploy to Server via SSH
              uses: appleboy/ssh-action@v0.1.5
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: ${{ secrets.SERVER_USER }}
                  password: ${{ secrets.SERVER_PASS }}
                  port: ${{ secrets.SERVER_SSH_PORT }}
                  script: |
                      docker pull ${{ secrets.DOCKERHUB_USERNAME }}/lb-discord-bot:latest
                      docker stop lb-discord-bot || true
                      docker rm lb-discord-bot || true
                      docker run -d \
                        --name lb-discord-bot \
                        --restart unless-stopped \
                        -e BOT_TOKEN='${{ secrets.DISCORD_BOT_TOKEN }}' \
                        -e LB_Bot_RMBTOKEN='${{ secrets.LB_BOT_RMBTOKEN }}' \
                        ${{ secrets.DOCKERHUB_USERNAME }}/lb-discord-bot:latest
